apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  database_password: {{ .Values.database_password | b64enc }}
  database_username: {{ .Values.database_username | b64enc }}
