apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecret-auth
data:
  database_password: {{ .Values.database_password | b64enc }}
  database_username: {{ .Values.database_username | b64enc }}
  database_host_name: {{ .Values.database_host_name | b64enc }}
  database_name: {{ .Values.database_name | b64enc }}

